#+BEGIN_SRC html
---
title: 讀capitalism without capital-- 理解未來的經濟趨勢 
date: 2018-08-23 00:32:00
tags: [ reading ]
---
#+END_SRC

* capitalism

** Gates note
我是在大約一周前在gates note上看到這本書的[[https://www.gatesnotes.com/Books/Capitalism-Without-Capital][介紹]]，雖然介紹文提到有很多經濟學的名詞，可能不是那麼好讀。但我讀起來並不會很生硬（更何況對我來說是外語）。最近選舉又要到了，很多候選人都在提如何讓經濟變好。我覺得每個想要活絡地方經濟的人，都要來讀讀這本書（或是看我寫的中文版導讀，哈）。書末的最後兩章，其實都是對政府官員喊話，如果要花大錢做科技園區，為什麼不花點小錢，來做這個未來趨勢的投資了。

** 摸不到的投資
我非經濟方面的專家，因此有些詞是我自己翻譯的，不知道這樣寫對不對。書中先解釋了什麼是摸不到、什麼是摸得到的資產。我們以前所認知的，譬如房子、車子、設備等等。而摸不到的就是軟體、你寫的文章、課程、流程、know-how。我們對於GDP或是對於評估經濟活絡的方式，過去都沒有把這些摸不到的投資納入，直到近十年，才開始有些學者對這方面有所評估。而且這些摸不到的資產，在一個公司倒閉要賣的時候，非常有可能是賣不出去的。有很多特性是和以前我們熟悉摸得到有很大的差別。譬如在募資方面、還有收益方面就有很大的落差。但我們都還未意識到。所以Bill Gates在他文章的title就寫：
#+BEGIN_QUOTE
Not enough people are paying attention to this economic trend
#+END_QUOTE

不太有人注意到的經濟趨勢。

的確，我們政府在花錢想要提升經濟時會花大錢蓋建設、設定科學園區，想要找的都是硬體廠商。這樣才可以做出成績。不過這是過去的老招了。如何面對新的時代？

** 4個s
- scalable
- sunk
- spinover
- synergies

這四個s就是這些摸不到產品的特色。我們拿軟體來說，軟體絕對比工廠還要容易規模化。譬如facebook 比汽車工廠更容易服務到一千萬人吧，但是如果facebook失敗了，就一毛錢也不值，汽車工廠有設備可賣、有汽車可賣，投資人失敗了還是錢拿得回來一部分；但軟體公司就什麼也沒有。spinover不曉得怎麼翻才好，外溢效應；最簡單的就是iphone的誕生，造就了samsung和htc等等手機廠商，他們只要抄（致敬）就好，或是中國的人人網、微信等等，一開始都是先模仿對手。synergies，可以翻成和他人的協作。汽車工廠就是賣車的，不太會有和其他人協作，但軟體可以跨界，可以有新的火花，譬如airbnb, uber就是新的跨界產生的。這些都是新的特性。

** 新的問題，新的解法
但問題來了，如果銀行要貸款給公司，要看公司有什麼可以扺押的，我有軟體可以抵押，但是「軟體」沒有成功就是一毛錢都不值啊…所以這些intangible investment很難成立。你說，難成立就算了啊，不要投資了。但是世界各國近十年在這些看不到的資產有重大的投資，比例較高的是美國和英國，你看矽谷滿滿的軟體公司。所以他們都是靠VC創投；但是創投也有些限制在。譬如創投就不想投錢在對抗瘧疾的新藥等等。書中作者就有提到，那就要靠著政府的力量來投資或是用大學研發的能量來做產學的合作。

此外，因為有外溢效應，東西很好被抄襲，所以政府要立法，有更好的智產權，保護這些人的權益，要有明確的禁止僱員跳槽後的「非競爭條款」，有好的保護措施。

因為需要有協作的可能，政府要提供coworking space, 房價要合理，讓更多人可以在城市裡和其他人有更多的交流。如果台灣有很多蚊子館、為什麼不拿出來，提供讓人有更多交流的可能性呢？

文中還有一些稅賦的討論，不過我看得很吃力，先行跳過了。

因為成功者會有規模化的效應，未來的世界更有可能是大者更大、富者越富。看看現在的google, apple, facebook, amazon就知道了。

但是小國家也有小國的機會，文中有提到新加坡和馬來西亞、在這方面開放的政策、政府出資投資摸不到的產業、智產權的保護、提供便宜好的住宿、讓人交流一起工作的空間，因為小國的政府動作更快。我們應該不是大國、應該在這方面要更加開放、動作要再快一點做出回應才是，除了蓋科學園區外，是不是可以再多做些什麼呢？

** 還有新的管理方式
這裡也有提到了，因為這些intangible asset需要大量的創造力，古早工業時代要求每個人做好做滿八小時的生產模式可能不合時宜，要讓這些人可以有更多的自主性。

書比較像是給政府的建議書、很多都是在比較高層次的討論，沒有對於個人的建議。不過，如果你對於這些摸不到的資產、還有未來十年的經濟樣貌好奇的話，值得一讀，書不厚，到此篇文章完成為止還沒有中文版。
